packages:
  - apps/*
  - services/*
  - packages/*
allowBuilds:
  '@parcel/watcher': true
  esbuild: true
  msgpackr-extract: true
minimumReleaseAgeExclude:
  - nodemailer@10.0.15
overrides:
  "@evolution-sdk/evolution": 0.5.13
